name: Deploy to Github Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Load cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn

      - name: Install dependencies
        run: yarn install

      - name: Build library
        run: |
          cd core
          yarn build

      - name: Build example-app
        run: |
          cd example-app
          yarn build

      - name: Run Cypress tests
        id: cypress
        uses: cypress-io/github-action@v2
        with:
          cache-key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          start: yarn --cwd ./example-app preview
          wait-on: 'http://localhost:5000'
          project: ./core
          browser: electron
          quiet: true

      - name: Export screenshots (on failure only)
        uses: actions/upload-artifact@v2.2.3
        if: failure()
        with:
          name: cypress-screenshots
          path: ./core/cypress/screenshots
          retention-days: 7

      - name: Export screen recordings (on failure only)
        uses: actions/upload-artifact@v2.2.3
        if: failure()
        with:
          name: cypress-videos
          path: ./core/cypress/videos
          retention-days: 7

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_ACTIONS_DEPLOY_KEY }}
          publish_dir: ./example-app/build